language: objective-c
# should give access to mac osx 10.10.4
osx_image: xcode7

# avoid timeouts during long gcc build
install: travis_wait

script:
  - brew tap riscv/riscv
  - brew install riscv-tools
  - brew test riscv-tools
  # now rebuild (instead of from pre-built binaries)
  - brew reinstall --build-from-source riscv-fesvr
  - brew reinstall --build-from-source riscv-isa-sim
  - brew reinstall --build-from-source riscv-gcc
  - brew reinstall --build-from-source riscv-pk
  - rm -f hello.c a.out
  - brew test riscv-tools
